[tool.poetry]
name = "example project"
version = "0.0.0"
description = "example project"
authors = ["Issy Codron <ic302@exeter.ac.uk>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
